### PR TITLE
Manually update slashes in flag names

### PR DESCRIPTION
**Pull request by anubisthejackle**
## Summary
This change updates slashes in flag names to allow fully qualified PHP class names to be used as flags (e.g. Alley\Interactive\Class becomes Alley%5CInteractive%5CClass) so they can be enabled and disabled using the menu bar.

## Notes for reviewers

None.

## Changelog entries

- **Changed**: Admin bar filter to manually update `\` to `%5C` to make it valid in a query parameter.

## Issue(s)

None.

### CODE REVIEW

**Review by jakewrfoster — COMMENTED** [review]
is the escaping necessary here? what about double escaped class references is that a likely occurrence?

**Comment by anubisthejackle** [comment]
@jakewrfoster Are you asking if it's necessary, or if it has to happen in this particular location?

It's necessary for the instance where we use `\` in a flag name (which we have done in some client projects), and it's important for that to happen in this location because `\` isn't converted, but instead appears to be filtered out when pushed to the URL in the Admin bar, which means when these flag names are used, these features cannot be enabled or disabled VIA the admin bar.

**Review by bchoplin — APPROVED** [review]
🤺

**Comment by srtfisher** [comment]
@anubisthejackle any reason we shouldn't merge this?

**Comment by anubisthejackle** [comment]
@srtfisher Nope, it just had tests that it was waiting for so I couldn't merge.

**Review by srtfisher — APPROVED** [review]

**Pull request merged**
